services:
  mysql_orders:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=cyna_orders'
      - 'MYSQL_PASSWORD=cyna_orders_pwd'
      - 'MYSQL_ROOT_PASSWORD=cyna_pwd'
      - 'MYSQL_USER=user_orders'
    ports:
      - '3309:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

