spring:
  application:
    name: subscriptions
  datasource:
    url: jdbc:mysql://localhost:3306/cyna_db
    username: cyna_user
    password: cyna_pwd
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

#  config:
#    import: configserver:${URL-CONFIG-SERVER:http://localhost:8888}
#  profiles:
#    active: ${PROFILE:local}

  docker:
    compose:
      file: compose.yaml
server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    preferIpAddress: false
    instance-id: ${spring.application.name}:${random.value}

logging:
  level:
    root: info
    web: debug
  file:
    name: ./target/cyna-orders.log

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

stripe:
  STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY:pk_test_51RD0MgRqA5M57Pbc8jw3RQjngdvI1g1tZV05aKYmtGNbnGh0WYSylqHDAyk7USvUT51osjfQ0yZnucFn2XZubPaE00sqVg9z4P}
  STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY:sk_test_51RD0MgRqA5M57PbckdBXhTZWzbRXIfqv6Vd2Vq5WMVpk9F4UzH2blBhywEeb7H4pG4u2XlsstCURX44pZyBNg1jV00Dyl1O9vn}
  STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET:whsec_08e553ba8667029c8ae146c2b92cf21c6793d2864a3a74397b1178262d98b2a1}
  STATIC_DIR: "../client"
  return_url: ${RETURN_URL:http://localhost:1234}

mailerSend:
  from: ${MAIL_USERNAME:wilfried@trial-ywj2lpnqzo1g7oqz.mlsender.net}
  support_email: ${MAIL_USERNAME:wilfried@trial-ywj2lpnqzo1g7oqz.mlsender.net}
  token: ${API_TOKEN:mlsn.d9038881333ff79e651de384e23449400c2ef9e55a9195efeb16a7bc027d1286}
  templates:
    generic_template:  "3z0vklo86e147qrx"
    generic_template_with_button: "jpzkmgq87o2g059v"
    email_verified: "jy7zpl998erl5vx6"

