spring:
  application:
    name: subscriptions
  datasource:
    url: jdbc:${JAWSDB_URL:mysql://cyna_db:3306/cyna_db}
    username: ${DB-USERNAME:cyna_user}
    password: ${DB-PASSWORD:cyna_pwd}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  docker:
    compose:
      file: compose.yaml
server:
  port: ${PORT:8083}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA-URI:http://eureka-server:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: ${HOST-AUTH-USERS:${spring.application.name}}
    instance-id: ${spring.application.name}:${random.value}
    preferIpAddress: false

logging:
  level:
    root: info
    web: debug
  file:
    name: ./target/cyna-orders.log

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

mailerSend:
  from: zodiaquestar@gmail.com
  support_email: support@test-86org8e8d2ngew13.mlsender.net
  super_admin: zodiaquestar@gmail.com
  token: "mlsn.bb6d1d29406fb4990121be59c181e45c23a0741696de1c9116ac5cc457b5d52a"
  templates:
    generic_template: "3vz9dlej3n74kj50"
    generic_template_with_button: "jpzkmgq87o2g059v"
    email_verified: "jy7zpl998erl5vx6"
stripe:
  publishable-key: pk_test_51RFIAlR4HDvdHnh3kjIJjPVIV0u1LRfhbGfqQpiGliWgIbXjkpPfHzeLLWjzK7vHu0VmTQqV4HYQYrvsG6G9KLOA00nADdiJ0E
  secret-key: sk_test_51RFIAlR4HDvdHnh3mtvzfNGinHxKEyaSvAc6WRpDQkt9twvPYY8kRjSh2MVLR8wv7LggsGWBD7M4Mbfj3LytC5Cy00W4oFSLc6
  webhook-secret: whsec_b445870c24c152547e2cf7fd46d6767b55c9ea956be6d42dea53676b7c9f10af
