services:
#  config-server:
#    container_name: 'config-server'
#    build: ./config-server
#    ports:
#      - '8888:8888'
#
#  eureka-server:
#    container_name: 'eureka-server'
#    build: ./EurekaServer
#    ports:
#      - '8761:8761'
#    depends_on:
#      - config-server
#
#  api-gateway:
#    container_name: 'api-gateway'
#    build: ./api-gateway
#    ports:
#      - '8080:8080'
#    depends_on:
#      - config-server
#      - eureka-server
#    environment:
#      - URL-CONFIG-SERVER=http://config-server:8888
#
#  auth-users:
#    container_name: 'auth-users'
#    build: ./auth-users
#    depends_on:
#      - config-server
#      - eureka-server
#      - cyna_db
#
#  products:
#    container_name: 'products'
#    build: ./products
#    ports:
#      - '8082:8082'
#    volumes:
#      - ./products/images:/home/images
#    environment:
#      - directory.images=/home/images
#      - static.location=/images
#    depends_on:
#      - config-server
#      - eureka-server
#      - cyna_db
#
#  subscriptions:
#    container_name: 'subscriptions'
#    build: ./subscriptions
#    ports:
#      - '8083:8083'
#    volumes:
#      - ./subscriptions/images:/home/images
#    environment:
#      - directory.images=/home/images
#      - static.location=/images
#    depends_on:
#      - config-server
#      - eureka-server
#      - cyna_db

  cyna_db:
    container_name: 'cyna_db'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=cyna_db'
      - 'MYSQL_PASSWORD=cyna_pwd'
      - 'MYSQL_ROOT_PASSWORD=cyna_pwd'
      - 'MYSQL_USER=cyna_user'
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - '3306:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
#    secrets:
#      - db-password

  phpmyadmin:
    container_name: 'phpmyadmin'
    image: phpmyadmin
    restart: always
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=cyna_db   # <<== AJOUT TRÈS IMPORTANT
      - PMA_PORT=3306    # <<== Facultatif, mais recommandé
volumes:
  db-data:
#secrets:
#  db-password:
#    external: true
