server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: auth-users
          uri: lb://auth-users
          predicates:
            - Path=/api/v1/auth/**

        - id: user-service
          uri: lb://auth-users
          predicates:
            - Path=/api/v1/user/**,/auth-users/**
          filters:
            - name: JwtAuth

        - id: products
          uri: lb://products
          predicates:
            - Path=/api/v1/products/**,/api/v1/categories/**,/products/**

        - id: orders
          uri: lb://orders
          predicates:
            - Path=/api/v1/orders/**,/orders/**
          filters:
            - name: JwtAuth

        - id: sav
          uri: lb://sav
          predicates:
            - Path=/api/v1/sav/**, /sav/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    preferIpAddress: false
    instance-id: ${spring.application.name}:${random.value}
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.netflix: DEBUG

  file:
    name: ./target/api-gateway.log

springdoc:
  api-docs:
    path: /aggregated-api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    urls:
      - name:  gateway-service
        url: /aggregated-api-docs
      - name: auth-users
        url: /auth-users/api-docs
      - name: products
        url: /products/api-docs