eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: ${EUREKA-URI:http://localhost:${PORT:8761}/eureka}

  instance:
    hostname: localhost
    prefer-ip-address: true

logging:
  level:
    root: warn
    com.netflix: OFF
    com.discovery: OFF