spring:
  application:
    name: orders
  datasource:
    url: jdbc:mysql://localhost:3306/cyna_orders
    username: user_orders
    password: cyna_orders_pwd
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  docker:
    compose:
      file: orders/compose.yaml
server:
  port: 8083

logging:
  level:
    root: ERROR
    web: DEBUG
    org:
      springframework:
        web: DEBUG
        security: DEBUG
  file:
    name: ./target/cyna-orders.log

stripe:
  STATIC_DIR: "../client"
  STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
  STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
  STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
