spring :
  application :
    name : config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/KFLandry/config-repo.git
          skip-ssl-validation: true
server:
  port: 8888

logging:
  level:
    web: debug
