spring:
  application:
    name: auth-users
  config:
    import: configserver:${URL:CONFIG-SERVER:http://localhost:8888}
  profiles:
    active: ${PROFILE:local}

endpoints:
  validate_email: ${FRONT_END_URL:http://localhost:8080}/api/v1/auth/validate-email
  validate_account: ${FRONT_END_URL:http://localhost:8080}/api/v1/auth/validate-account
  password_forgot: ${FRONT_END_URL:http://localhost:8080}/api/v1/auth/password-forgot

mailerSend:
  from: ${MAIL_USERNAME}
  support_email: ${SUPPORT_MAIL}
  super_admin: ${SUPER_ADMIN}
  token: ${API_TOKEN}

templates:
  generic_template: ${GENERIC_TEMPLATE}
  generic_template_with_button: ${GENERIC_TEMPLATE_BUTTON}
  email_verified: ${EMAIL_VERIFIED}
